### PR TITLE
Support swift package manager

### PR DESCRIPTION
**Pull request by klundberg**
- Add swift package manager support
- Fix loading storyboard when built with SPM, remove unused resources

### Description

Addresses #26

This PR adds a Package.swift file to the repo root, deletes some old xibs and html files that were no longer used by the library (to make crafting the package.swift easier), and adds SPM-specific support for loading storyboards from the bundle when built with SPM.

No changes should be necessary for the podspec, or for future carthage support, for this to work with SPM.

I verified with an example app that this worked as expected, but had difficulty making the example app + project changes necessary work across xcode launches. Making that work would require restructuring the directory structure of the repo which I preferred not to do, to keep this PR at a manageable size. If that is desired I could look into an alternate way to structure the spm example project.

---
### Checklist

- [ ] The steps for distribution have been follow [here](https://www.notion.so/adasupport/Distribution-3a9dfc90c9b3449781b6f9c825f1dee8).
- [ ] A [Release Note](https://www.notion.so/adasupport/Creating-Release-Notes-36906dfa8a2b4f10a31dc23b8d46681a) has been drafted and published after merging to master.
- [ ] PR has been labelled with its [impact level](https://www.notion.so/adasupport/Release-Management-Change-Definitions-c5a239ae075d4cc49bb1066f3e11f39f#b0af5e2c7bc7481a82303fa70b12e4f6)

### CODE REVIEW

**Review by mccarron — APPROVED** [review]
Love the changes, this worked flawlessly with our complicated project. Hopefully someone from Ada can get this merged in.

Maybe now we can get off of Cocoapods finally. 🙌

**Comment by morluna** [comment]
We also integrated these changes to our project and it's working well! Please get this merged soon 🚀

**Review by morluna — APPROVED** [review]

**Comment by morluna** [comment]
CC @michaellazz @klundberg ^^

**Comment by michaellazz** [comment]
We are currently reviewing the need for Swift Package Manager internally but will not be merging this PR at this time. I'll be closing this PR but may revisit it if we plan on supporting swift package manager and will open a new PR with the changes at that time.

**Pull request closed without merging**
